import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment
from openpyxl.comments import Comment
import os

def create_dirty_excel(filename="dirty_test.xlsx"):
    wb = Workbook()
    ws = wb.active
    ws.title = "Sales_Data_Q1"

    # --- Add Pre-header Noise ---
    ws["A1"] = "Confidential Report"
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"] = "Generated by: System X"
    ws["A3"] = "Date: 2026-02-17"
    ws.merge_cells("A1:D1")

    # --- Add Actual Header at Row 6 ---
    headers = ["ID", "Product Name", "Region", "Revenue", "Status"]
    header_row = 6
    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=header_row, column=col_num, value=header)
        cell.font = Font(bold=True)
        cell.fill = PatternFill(start_color="CCCCCC", end_color="CCCCCC", fill_type="solid")

    # --- Add Data ---
    data = [
        [101, "Widget A", "North", 5000, "Approved"],
        [102, "Widget B", "South", 3200, "Pending"],
        [103, "Gadget X", "East", 8100, "Rejected"],
        [104, "Gadget Y", "West", 4500, "Approved"],
        [None, None, None, None, None], # Empty row
        [105, "Gizmo Z", "North", 1200, "Approved"],
    ]

    for i, row_data in enumerate(data, 1):
        for j, value in enumerate(row_data, 1):
            cell = ws.cell(row=header_row + i, column=j, value=value)
            
            # Add semantic colors
            if value == "Approved":
                cell.fill = PatternFill(start_color="00FF00", end_color="00FF00", fill_type="solid") # Green
            elif value == "Rejected":
                cell.fill = PatternFill(start_color="FF0000", end_color="FF0000", fill_type="solid") # Red
            elif value == "Pending":
                 cell.fill = PatternFill(start_color="FFFF00", end_color="FFFF00", fill_type="solid") # Yellow

            # Add comment
            if value == 8100:
                cell.comment = Comment("Outlier value due to bulk order", "System")

    # --- Add Second Sheet (for Global Context testing) ---
    ws2 = wb.create_sheet("Config_Data")
    ws2["A1"] = "Setting"
    ws2["B1"] = "Value"
    ws2["A2"] = "Max Users"
    ws2["B2"] = 100
    ws2["A3"] = "Theme"
    ws2["B3"] = "Dark"

    # --- Save ---
    wb.save(filename)
    print(f"Created {filename}")

if __name__ == "__main__":
    create_dirty_excel()
